githubRepoOwner: happycollision
githubRepoName: trigger.happycollision.com
githubHost: github.com
requireChecks: true
requireApproval: true
mergeMethod: rebase
mergeQueue: false
forceFetchTags: false
